name: 🐛 Bug Report (Backend)
description: Riporta un problema relativo a endpoint o logica di business
labels: [bug, backend]
body:
  - type: textarea
    attributes:
      label: Descrizione del problema
      description: Spiega quale API o endpoint causa un errore
      placeholder: Es. Il POST su `/auth/login` restituisce errore 500...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Come riprodurre il bug
      description: Passaggi per riprodurre il problema
    validations:
      required: true

  - type: textarea
    attributes:
      label: Stacktrace / Log (se presenti)
      description: Incolla eventuali errori del server
