blank_issues_enabled: true
contact_links:
  - name: 💬 Discussioni generali o idee
    url: https://github.com/NOMEORG/NOMEREPO/discussions
    about: Per domande aperte o brainstorming, usa le Discussions
