name: ⚙️ Richiesta API / Logica Backend
description: Proponi l'aggiunta o modifica relativa a endpoint o logica lato server
labels: [enhancement, backend]
body:
  - type: textarea
    attributes:
      label: Descrizione
      placeholder: Es. Serve una nuova API GET `/users/:id/stats` per la dashboard...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Dipendenze lato frontend
      description: Specifica se il frontend ha già bisogno di questa funzionalità o come dovrebbe usarla
