"""aggiunte variabili arrivo e numero tappa in gruppo

Revision ID: 0519931ccecc
Revises: d2f82548cdb1
Create Date: 2024-10-10 18:01:26.723687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0519931ccecc'
down_revision: Union[str, None] = 'd2f82548cdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('stage_number', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('is_arived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'is_arived')
    op.drop_column('groups', 'stage_number')
    # ### end Alembic commands ###
