"""aggiunti orari effettivi partenza fine gruppo

Revision ID: 08c85ed83431
Revises: 13c22af60bc4
Create Date: 2024-11-25 22:02:25.371978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c85ed83431'
down_revision: Union[str, None] = '13c22af60bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gruppi', sa.Column('orario_partenza_effettivo', sa.String(), nullable=True))
    op.add_column('Gruppi', sa.Column('orario_fine_effettivo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gruppi', 'orario_fine_effettivo')
    op.drop_column('Gruppi', 'orario_partenza_effettivo')
    # ### end Alembic commands ###
