"""aggiunto campo genitore in iscrizione

Revision ID: 0d0bf6f2141a
Revises: a0fdab3455e3
Create Date: 2025-04-18 21:28:51.440157

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d0bf6f2141a'
down_revision: Union[str, None] = 'a0fdab3455e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Iscrizioni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genitore_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_iscrizione_genitore', 'Genitori', ['genitore_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Iscrizioni', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iscrizione_genitore', type_='foreignkey')
        batch_op.drop_column('genitore_id')
    # ### end Alembic commands ###
