"""aggiunte presenze orientati

Revision ID: 13c22af60bc4
Revises: 82d2f7cc72dc
Create Date: 2024-11-18 12:38:31.092150

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '13c22af60bc4'
down_revision: Union[str, None] = '82d2f7cc72dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
