"""corretto log gruppi-tappe

Revision ID: 1d360c1f5196
Revises: 48d8b21a95be
Create Date: 2025-06-07 08:26:57.781073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d360c1f5196'
down_revision: Union[str, None] = '48d8b21a95be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LogGruppiTappe') as batch_op:
        batch_op.create_foreign_key('fk_loggruppi_gruppi', 'Gruppi', ['gruppo_id'], ['id'])
        batch_op.create_foreign_key('fk_loggruppi_tappe', 'Tappe', ['tappa_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LogGruppiTappe') as batch_op:
        batch_op.drop_constraint('fk_loggruppi_gruppi', type_='foreignkey')
        batch_op.drop_constraint('fk_loggruppi_tappe', type_='foreignkey')
    # ### end Alembic commands ###