"""agiunti gruppi e visitatori

Revision ID: 2274b802e551
Revises: 288b9f8c8850
Create Date: 2024-10-22 08:43:50.437070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2274b802e551'
down_revision: Union[str, None] = '288b9f8c8850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percorsiDiStudi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gruppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('oraPartenza', sa.String(), nullable=False),
    sa.Column('percorsoDiStudi_id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['percorsoDiStudi_id'], ['percorsiDiStudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentiVisitatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Cognome', sa.String(), nullable=False),
    sa.Column('ScuolaProvenienza', sa.String(), nullable=False),
    sa.Column('Presenza', sa.Boolean(), nullable=False),
    sa.Column('percorsoDiInteresse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['percorsoDiInteresse_id'], ['percorsiDiStudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codiciGruppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partecipanti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studenteVisitatore_id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['studenteVisitatore_id'], ['studentiVisitatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_utenti_nome', table_name='utenti')
    op.create_index(op.f('ix_utenti_username'), 'utenti', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utenti_username'), table_name='utenti')
    op.create_index('ix_utenti_nome', 'utenti', ['username'], unique=1)
    op.drop_table('partecipanti')
    op.drop_table('codiciGruppi')
    op.drop_table('studentiVisitatori')
    op.drop_table('gruppi')
    op.drop_table('percorsiDiStudi')
    # ### end Alembic commands ###
