"""aggiunta association ragazzi-indirizzi di interesse

Revision ID: 245c6c2fa950
Revises: 2f8e83ac5687
Create Date: 2025-03-03 12:21:34.444532

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '245c6c2fa950'
down_revision: Union[str, None] = '2f8e83ac5687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ragazzi', schema=None) as batch_op:
        batch_op.drop_column('indirizzoDiInteresse_1_id')
        batch_op.drop_column('indirizzoDiInteresse_2_id')
        batch_op.drop_column('indirizzoDiInteresse_3_id')

    op.create_table('association_ragazzi_indirizzi',
                    sa.Column('ragazzo_id', sa.Integer(), nullable=True),
                    sa.Column('indirizzoDiInteresse_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['indirizzoDiInteresse_id'], ['Indirizzi.id'], ),
                    sa.ForeignKeyConstraint(['ragazzo_id'], ['Ragazzi.id'], )
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_ragazzi_indirizzi')

    with op.batch_alter_table('Ragazzi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indirizzoDiInteresse_1_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('indirizzoDiInteresse_2_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('indirizzoDiInteresse_3_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ragazzi_indirizzoDiInteresse_1', 'Indirizzi', ['indirizzoDiInteresse_1_id'],
                                    ['id'])
        batch_op.create_foreign_key('fk_ragazzi_indirizzoDiInteresse_2', 'Indirizzi', ['indirizzoDiInteresse_2_id'],
                                    ['id'])
        batch_op.create_foreign_key('fk_ragazzi_indirizzoDiInteresse_3', 'Indirizzi', ['indirizzoDiInteresse_3_id'],
                                    ['id'])
    # ### end Alembic commands ###
