"""migliorata struttura fascie orarie

Revision ID: 2c8ee1b8efb7
Revises: 0d0bf6f2141a
Create Date: 2025-05-02 17:18:03.410623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2c8ee1b8efb7'
down_revision: Union[str, None] = '0d0bf6f2141a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Gruppi') as batch_op:
        batch_op.add_column(sa.Column('fasciaOraria_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('gruppi_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('fk_gruppi_fasceorarie', 'FasceOrarie', ['fasciaOraria_id'], ['id'])
        batch_op.drop_column('orario_partenza')
        batch_op.drop_column('percorso_id')
        batch_op.drop_column('data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Gruppi') as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('percorso_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('orario_partenza', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('fk_gruppi_fasceorarie', type_='foreignkey')
        batch_op.create_foreign_key('fk_gruppi_percorsi', 'Percorsi', ['percorso_id'], ['id'])
        batch_op.drop_column('fasciaOraria_id')
    # ### end Alembic commands ###
