"""Rimosso orientato

Revision ID: 2f8e83ac5687
Revises: 6a71f9e697ec
Create Date: 2025-03-01 20:36:17.254656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8e83ac5687'
down_revision: Union[str, None] = '6a71f9e697ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Association_orientati_gruppi')
    op.drop_table('Orientati')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orientati',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cognome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('scuolaDiProvenienza_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['scuolaDiProvenienza_id'], ['ScuoleDiProvenienza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Association_orientati_gruppi',
    sa.Column('idOrientato', sa.INTEGER(), nullable=True),
    sa.Column('idGruppo', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['idGruppo'], ['Gruppi.id'], ),
    sa.ForeignKeyConstraint(['idOrientato'], ['Orientati.id'], )
    )
    # ### end Alembic commands ###
