"""aggiunta gestione stato tappe in gruppi

Revision ID: 3db2cdd9a0ed
Revises: d4a85be5e1c6
Create Date: 2024-11-15 19:14:12.922540

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3db2cdd9a0ed'
down_revision: Union[str, None] = 'd4a85be5e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gruppi', sa.Column('numero_tappa', sa.Integer(), nullable=True))
    op.add_column('Gruppi', sa.Column('arrivato', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gruppi', 'arrivato')
    op.drop_column('Gruppi', 'numero_tappa')
    # ### end Alembic commands ###
