"""aggiunte tabelle

Revision ID: 59ad24a69c1c
Revises: 
Create Date: 2024-10-23 12:29:19.912471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ad24a69c1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percorsiDiStudi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gruppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('oraPartenza', sa.String(), nullable=False),
    sa.Column('percorsoDiStudi_id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['percorsoDiStudi_id'], ['percorsiDiStudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indirizzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('percorsoDiStudi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['percorsoDiStudi_id'], ['percorsiDiStudi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentiVisitatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Cognome', sa.String(), nullable=False),
    sa.Column('ScuolaProvenienza', sa.String(), nullable=False),
    sa.Column('Presenza', sa.Boolean(), nullable=False),
    sa.Column('indirizzo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indirizzo_id'], ['indirizzi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('temporaneo', sa.Boolean(), nullable=False),
    sa.Column('indirizzo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indirizzo_id'], ['indirizzi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_username'), 'utenti', ['username'], unique=True)
    op.create_table('codiciGruppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partecipanti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studenteVisitatore_id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['studenteVisitatore_id'], ['studentiVisitatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(
        """
        INSERT INTO utenti (username, hashed_password, admin, temporaneo)
        VALUES ('admin', '$2b$12$Fyp.CIuqwcrqs09Oklz71eVMcwHBTP11x3FBj.B6LiUl7dxEYuaO2', true, false)
        """
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO utenti (username, hashed_password, admin, temporaneo)
        VALUES ('user', '$2b$12$KYaTyisWLNtSnGOoo1B.3ue7oN/6abk0BeZupZX1BVKNf.JsTQrlW', false, false) 
        """
    )  # password: user

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partecipanti')
    op.drop_table('codiciGruppi')
    op.drop_index(op.f('ix_utenti_username'), table_name='utenti')
    op.drop_table('utenti')
    op.drop_table('studentiVisitatori')
    op.drop_table('indirizzi')
    op.drop_table('gruppi')
    op.drop_table('percorsiDiStudi')
    # ### end Alembic commands ###
