"""aggiunta tabella utente

Revision ID: 78c60cfd8dc6
Revises: 
Create Date: 2024-10-19 22:13:46.413616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c60cfd8dc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.execute(
        """
        INSERT INTO users (username, email, hashed_password, is_admin, name, surname)
        VALUES ('admin', 'admin@admin.com', '$2b$12$Fyp.CIuqwcrqs09Oklz71eVMcwHBTP11x3FBj.B6LiUl7dxEYuaO2', true, 'Admin', 'Admin')
        """
    )  # password: admin

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute("DELETE FROM users WHERE username = 'admin'")
    # ### end Alembic commands ###
