"""isUfficiale in scuolaDiProvenienza

Revision ID: 7a89f1f49526
Revises: a47239208574
Create Date: 2025-04-14 11:31:32.919759

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7a89f1f49526'
down_revision: Union[str, None] = 'a47239208574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ScuoleDiProvenienza', sa.Column('isUfficiale', sa.Boolean(), nullable=False,
                                                   server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ScuoleDiProvenienza', 'isUfficiale')
    # ### end Alembic commands ###
