"""resi genitore_id e scuolaDiProvenienza_id ragazzo opzionali

Revision ID: 8ea345399f5e
Revises: 1d360c1f5196
Create Date: 2025-06-09 10:27:45.619592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea345399f5e'
down_revision: Union[str, None] = '1d360c1f5196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ragazzi') as batch_op:
        batch_op.alter_column('scuolaDiProvenienza_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('genitore_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ragazzi') as batch_op:
        batch_op.alter_column('genitore_id',
                            existing_type=sa.INTEGER(),
                            nullable=False)
        batch_op.alter_column('scuolaDiProvenienza_id',
                            existing_type=sa.INTEGER(),
                            nullable=False)
    # ### end Alembic commands ###
