"""aggiunto orario partenza gruppo

Revision ID: 992a670c5df1
Revises: ca439a6160f6
Create Date: 2024-11-08 18:02:46.818844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992a670c5df1'
down_revision: Union[str, None] = 'ca439a6160f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gruppi', sa.Column('orario_partenza', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gruppi', 'orario_partenza')
    # ### end Alembic commands ###
