"""campo data modificato formato in date

Revision ID: a0fdab3455e3
Revises: 7a89f1f49526
Create Date: 2025-04-18 19:38:04.546627

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0fdab3455e3'
down_revision: Union[str, None] = '7a89f1f49526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Date_new',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('data', sa.Date(), nullable=False),
    )
    op.execute('INSERT INTO Date_new (id, data) SELECT id, data FROM Date')
    op.drop_table('Date')
    op.rename_table('Date_new', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Date_old',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('data', sa.VARCHAR(length=255), nullable=False),
    )
    op.execute('INSERT INTO Date_old (id, data) SELECT id, data FROM Date')
    op.drop_table('Date')
    op.rename_table('Date_old', 'Date')
    # ### end Alembic commands ###
