"""Rimossi logUtente

Revision ID: c90c5e48dfc6
Revises: 25561eb084c4
Create Date: 2025-02-12 12:28:19.535295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c90c5e48dfc6'
down_revision: Union[str, None] = '25561eb084c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_action_logs_id', table_name='user_action_logs')
    op.drop_index('ix_user_action_logs_utente_id', table_name='user_action_logs')
    op.drop_table('user_action_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('utente_id', sa.INTEGER(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=8), nullable=False),
    sa.Column('azione', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dati', sqlite.JSON(), nullable=True),
    sa.Column('orario', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['Utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_action_logs_utente_id', 'user_action_logs', ['utente_id'], unique=False)
    op.create_index('ix_user_action_logs_id', 'user_action_logs', ['id'], unique=False)
    # ### end Alembic commands ###
