"""aggiunto percorso di studi

Revision ID: d3336819f54c
Revises: 0eae6753917e
Create Date: 2024-10-21 21:15:24.129216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3336819f54c'
down_revision: Union[str, None] = '0eae6753917e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percorsiDiStudi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gruppi', sa.Column('percorsoDiStudi_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gruppi', 'percorsiDiStudi', ['percorsoDiStudi_id'], ['id'])
    op.drop_index('ix_utenti_nome', table_name='utenti')
    op.create_index(op.f('ix_utenti_username'), 'utenti', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utenti_username'), table_name='utenti')
    op.create_index('ix_utenti_nome', 'utenti', ['username'], unique=1)
    op.drop_constraint(None, 'gruppi', type_='foreignkey')
    op.drop_column('gruppi', 'percorsoDiStudi_id')
    op.drop_table('percorsiDiStudi')
    # ### end Alembic commands ###
