"""aggiunto codice orientatore

Revision ID: d4a85be5e1c6
Revises: b008400811d1
Create Date: 2024-11-13 09:43:34.069123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a85be5e1c6'
down_revision: Union[str, None] = 'b008400811d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orientatori', sa.Column('codice', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orientatori', 'codice')
    # ### end Alembic commands ###
