"""aggiunti logs utente

Revision ID: dd11de38f4cf
Revises: 3db2cdd9a0ed
Create Date: 2024-11-16 00:10:34.675930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd11de38f4cf'
down_revision: Union[str, None] = '3db2cdd9a0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
